import { Button } from "@/components/ui/button";
import { Sparkles, AlertTriangle, CalendarDays } from "lucide-react";
import Link from "next/link";
import { GeneratePlanClient } from "./GeneratePlanClient";
import { db } from "@/db";
import { users, wellnessPlans } from "@/db/schema";
import { eq, desc } from "drizzle-orm";
import { currentUser } from "@clerk/nextjs/server";
import ReactMarkdown from "react-markdown";

export default async function DashboardPage() {
    const clerkUser = await currentUser();
    let latestPlan = null;
    let hasPlan = false;

    if (clerkUser) {
        const userRecord = await db.query.users.findFirst({
            where: eq(users.clerkId, clerkUser.id)
        });
        if (userRecord) {
            const planRecords = await db.query.wellnessPlans.findMany({
                where: eq(wellnessPlans.userId, userRecord.id),
                orderBy: [desc(wellnessPlans.createdAt)],
                limit: 1,
            });
            if (planRecords.length > 0) {
                latestPlan = planRecords[0].planContent;
                hasPlan = true;
            }
        }
    }

    return (
        <div className="space-y-10 animate-in fade-in slide-in-from-bottom-4 duration-700">
            <header className="flex flex-col md:flex-row md:items-end justify-between gap-4">
                <div>
                    <h1 className="text-4xl font-extrabold tracking-tight text-slate-900 dark:text-slate-50">Welcome Back.</h1>
                    <p className="text-slate-500 mt-2 text-lg">Your wellness logistics dashboard is ready for optimization.</p>
                </div>
                <Link href="/dashboard/history">
                    <Button size="lg" className="bg-white text-slate-900 border border-slate-200 hover:bg-slate-50 shadow-sm dark:bg-slate-900 dark:text-white dark:border-slate-800 dark:hover:bg-slate-800 font-semibold gap-2">
                        <CalendarDays className="w-4 h-4" /> View History
                    </Button>
                </Link>
            </header>

            {/* Medical Disclaimer Alert - Premium UI */}
            <div className="relative overflow-hidden bg-gradient-to-r from-amber-500/10 to-orange-500/5 border border-amber-500/20 rounded-2xl p-6 shadow-lg shadow-amber-500/5">
                <div className="absolute top-0 right-0 p-4 opacity-10">
                    <AlertTriangle className="w-24 h-24 text-amber-500" />
                </div>
                <div className="relative z-10 flex items-start gap-4">
                    <div className="p-3 bg-amber-500/20 rounded-xl">
                        <AlertTriangle className="w-6 h-6 text-amber-600 dark:text-amber-400" />
                    </div>
                    <div>
                        <h3 className="text-amber-900 dark:text-amber-300 font-bold text-lg mb-1">Important Medical Disclaimer</h3>
                        <p className="text-amber-800/80 dark:text-amber-500/80 text-sm leading-relaxed max-w-3xl">
                            The logistics generated by this engine are for general wellness purposes only and do <strong>not</strong> substitute for professional medical advice, formal clinical diagnoses, or treatment plans. Always consult a healthcare professional before altering your diet, exercise routine, or lifestyle.
                        </p>
                    </div>
                </div>
            </div>

            {/* Main Action Area */}
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">

                {/* Generator Card */}
                <div className="lg:col-span-2 relative overflow-hidden bg-slate-900 dark:bg-slate-900/50 rounded-3xl border border-slate-800 dark:border-white/10 shadow-2xl p-8 lg:p-12 flex flex-col justify-center min-h-[300px]">
                    {/* Card Gradients */}
                    <div className="absolute top-0 left-0 w-full h-full bg-gradient-to-br from-emerald-500/10 via-transparent to-cyan-500/10 pointer-events-none" />
                    <div className="absolute -bottom-24 -right-24 w-64 h-64 bg-emerald-500/20 blur-[80px] rounded-full pointer-events-none" />

                    <div className="relative z-10 max-w-lg">
                        <div className="inline-flex items-center justify-center p-3 bg-white/10 border border-white/20 rounded-2xl mb-6 shadow-xl backdrop-blur-md">
                            <Sparkles className="w-8 h-8 text-emerald-400" />
                        </div>
                        <h2 className="text-3xl font-extrabold text-white mb-4 leading-tight">Generate Your New Routine</h2>
                        <p className="text-slate-400 text-lg mb-8 leading-relaxed">
                            Our AI engine will cross-reference your latest metrics against current wellness protocols to synthesize a customized daily schedule.
                        </p>
                        <GeneratePlanClient />
                    </div>
                </div>

                {/* Quick Stats Sidebar Card */}
                <div className="bg-white/50 backdrop-blur-xl dark:bg-slate-900/50 rounded-3xl border border-slate-200/50 dark:border-white/10 shadow-xl p-8 flex flex-col justify-between hidden md:flex">
                    <div>
                        <h3 className="text-lg font-bold text-slate-900 dark:text-white mb-6">Profile Status</h3>
                        <div className="space-y-4">
                            <div className="flex justify-between items-center pb-4 border-b border-slate-200 dark:border-slate-800">
                                <span className="text-slate-500">Completeness</span>
                                <span className="font-semibold text-emerald-600 dark:text-emerald-400">100%</span>
                            </div>
                            <div className="flex justify-between items-center pb-4 border-b border-slate-200 dark:border-slate-800">
                                <span className="text-slate-500">Last Synced</span>
                                <span className="font-semibold text-slate-900 dark:text-white">Just now</span>
                            </div>
                        </div>
                    </div>
                    <div className="mt-8 p-4 bg-slate-100 dark:bg-white/5 rounded-2xl border border-slate-200 dark:border-white/10">
                        <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
                            Keep your profile metrics updated weekly for the most accurate AI generation results.
                        </p>
                    </div>
                </div>
            </div>

            {hasPlan && latestPlan && (
                <div className="mt-12">
                    <h2 className="text-2xl font-bold mb-6 text-slate-900 dark:text-white flex items-center gap-2">
                        <Sparkles className="w-6 h-6 text-emerald-500" />
                        Your Latest Wellness Plan
                    </h2>
                    <div className="bg-white dark:bg-slate-900 rounded-3xl p-8 lg:p-12 border border-slate-200 dark:border-slate-800 shadow-xl prose prose-slate dark:prose-invert max-w-none prose-headings:text-emerald-700 dark:prose-headings:text-emerald-400 prose-a:text-cyan-500">
                        <ReactMarkdown>{latestPlan}</ReactMarkdown>
                    </div>
                </div>
            )}

        </div>
    );
}
